//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_FILES
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_1
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string Code { get; set; }
    
        public virtual add_1 add_1 { get; set; }
    }
}
