//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table1
    {
        public int Account_Number { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Account_Holdername { get; set; }
        [Required(ErrorMessage = "Email-Id is required")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string Confirm_Password { get; set; }
        //[Range((0-9),10)]
        public Nullable<long> Mobile_No { get; set; }
        [Required(ErrorMessage = "PAN is required")]
        [StringLength(9)]
        public string PAN { get; set; }
        [Required(ErrorMessage = "Aadhar is required")]
        //[Range((0-9),12)]
        public Nullable<long> Aadhaar { get; set; }
        public string Address { get; set; }
    }
}
