//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserReg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegistrationTable123
    {
        public int AccountId { get; set; }
        [Required(ErrorMessage ="Account Holder Name is required")]
        public string AccountHoldername { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string LoginErrorMsg { get; set; }
    }
}
